import { describe, expect, it } from 'vitest';
import { ctsCbcDecrypt, ctsCbcEncrypt } from '../src/crypto/cts';
import { fromHex, toHex } from './helpers';

/**
 * AES-CBC with ciphertext stealing (RFC 3962 / NIST SP 800-38A Addendum).
 * The defining property: ciphertext length exactly equals plaintext length
 * for any input of at least one block, with no padding expansion.
 */
function fixedKey(): Uint8Array {
  const k = new Uint8Array(32);
  for (let i = 0; i < 32; i += 1) k[i] = (i * 7 + 1) & 0xff;
  return k;
}

function pattern(len: number): Uint8Array {
  const p = new Uint8Array(len);
  for (let i = 0; i < len; i += 1) p[i] = (i * 13 + 5) & 0xff;
  return p;
}

describe('CTS-CBC round-trips across lengths', () => {
  const key = fixedKey();
  // 16 = exactly one block; 17/31/33/47 exercise the stealing path; 32/48 are
  // exact multiples (CBC with the last two blocks swapped); 100 is a long mixed case.
  for (const len of [16, 17, 31, 32, 33, 47, 48, 64, 100]) {
    it(`length ${len} round-trips and preserves length`, async () => {
      const pt = pattern(len);
      const ct = await ctsCbcEncrypt(key, pt);
      expect(ct.length).toBe(len);
      const back = await ctsCbcDecrypt(key, ct);
      expect(toHex(back)).toBe(toHex(pt));
    });
  }
});

// Published wire bytes, not ciphertext generated by the implementation under test.
// RFC 3962 Appendix B: https://www.rfc-editor.org/rfc/rfc3962.html#appendix-B
describe('RFC 3962 Appendix B CTS known-answer vectors', () => {
  const key = fromHex('636869636b656e207465726979616b69');
  const message = new TextEncoder().encode("I would like the General Gau's Chicken, please, and wonton soup.");
  const vectors = [
    { length: 17, ciphertext: 'c6353568f2bf8cb4d8a580362da7ff7f97' },
    { length: 31, ciphertext: 'fc00783e0efdb2c1d445d4c8eff7ed2297687268d6ecccc0c07b25e25ecfe5' },
    { length: 32, ciphertext: '39312523a78662d5be7fcbcc98ebf5a897687268d6ecccc0c07b25e25ecfe584' },
    { length: 47, ciphertext: '97687268d6ecccc0c07b25e25ecfe584b3fffd940c16a18c1b5549d2f838029e39312523a78662d5be7fcbcc98ebf5' },
    { length: 48, ciphertext: '97687268d6ecccc0c07b25e25ecfe5849dad8bbb96c4cdc03bc103e1a194bbd839312523a78662d5be7fcbcc98ebf5a8' },
    { length: 64, ciphertext: '97687268d6ecccc0c07b25e25ecfe58439312523a78662d5be7fcbcc98ebf5a84807efe836ee89a526730dbc2f7bc8409dad8bbb96c4cdc03bc103e1a194bbd8' },
  ];
  for (const vector of vectors) {
    // Each vector uses the corresponding prefix of the 64-byte message.
    const plaintext = new Uint8Array(vector.length);
    plaintext.set(message.subarray(0, vector.length));
    it(`encrypts ${vector.length} bytes to the published ciphertext without mutating input`, async () => {
      const original = toHex(plaintext);
      expect(toHex(await ctsCbcEncrypt(key, plaintext))).toBe(vector.ciphertext);
      expect(toHex(plaintext)).toBe(original);
    });
    it(`decrypts the published ${vector.length}-byte ciphertext without mutating input`, async () => {
      const ciphertext = fromHex(vector.ciphertext);
      expect(toHex(await ctsCbcDecrypt(key, ciphertext))).toBe(toHex(plaintext));
      expect(toHex(ciphertext)).toBe(vector.ciphertext);
    });
  }
});

describe('RFC 3962 single-block exception', () => {
  // FIPS-197 Appendix C.3 AES-256 vector; with zero IV a single block is ECB.
  const key = fromHex('000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f');
  const plaintext = fromHex('00112233445566778899aabbccddeeff');
  const ciphertext = fromHex('8ea2b7ca516745bfeafc49904b496089');
  it('encrypts one block without swapping', async () => {
    expect(toHex(await ctsCbcEncrypt(key, plaintext))).toBe(toHex(ciphertext));
  });
  it('decrypts one block without swapping', async () => {
    expect(toHex(await ctsCbcDecrypt(key, ciphertext))).toBe(toHex(plaintext));
  });
});

describe('CTS-CBC edge behaviour', () => {
  it('rejects input shorter than one block on encrypt', async () => {
    await expect(ctsCbcEncrypt(fixedKey(), new Uint8Array(15))).rejects.toThrow();
  });

  it('rejects input shorter than one block on decrypt', async () => {
    await expect(ctsCbcDecrypt(fixedKey(), new Uint8Array(15))).rejects.toThrow();
  });

  it('a single bit flip in the ciphertext changes the recovered plaintext', async () => {
    const key = fixedKey();
    const pt = pattern(40);
    const ct = await ctsCbcEncrypt(key, pt);
    ct[0] ^= 0x80;
    const back = await ctsCbcDecrypt(key, ct);
    expect(toHex(back)).not.toBe(toHex(pt));
  });
});
